use_frameworks!

target 'BZLib_Example' do
  pod 'BZLib', :path => '../'

  target 'BZLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
